#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#
debug: false

spring:
  profiles:
     include: oauth
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*, error/*
  ## H2 Servlet setting
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /admin/h2

            
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update #create #update #create-drop  

  main:
    allow-bean-definition-overriding: true



# Turn off Security for Actuator:
management:
  security:
    enabled: false


##---------------------------------------------------------------------------##
